### ISSUE TITLE
unhandled case where sunspec models dict is empty.. 

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#310]
```
[Logs]    [2024-11-21T08:39:11.881Z] [web] INFO:server.devices.inverters.ModbusSunspec:Models: {}
[Logs]    [2024-11-21T08:39:11.884Z] [web] ERROR:server.tasks.openDevicePerpetualTask:Exception opening a device: 'SunSpecModbusClientDeviceTCP' object has no attribute 'common''Traceback (most recent call last):\n  File "/server/tasks/openDevicePerpetualTask.py", line 44, in execute\n    if self.device.connect():\n       ^^^^^^^^^^^^^^^^^^^^^\n  File "/server/devices/Device.py", line 22, in connect\n    return self._connect(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/server/devices/inverters/ModbusSunspec.py", line 102, in _connect\n    self.sn = self.client.common[0].SN.value\n              ^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sunspec2/device.py", line 725, in __getattr__\n    raise AttributeError("\'%s\' object has no attribute \'%s\'" % (self.__class__.__name__, attr))\nAttributeError: \'SunSpecModbusClientDeviceTCP\' object has no attribute \'common\''
```

**Comment by davmoz** [comment]
This was partially fixed when we moved back to device MAC instead of device SN, but models can still be empty.

We now return `false` when models is empty, and `openDevicePerpetualTask` will attempt to open again 5 seconds later.
